name: building_tests
on: [ push ]
jobs:
  building_gtests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: build
        shell: bash
        run: |
          git submodule update --init --recursive
          cmake -B build
          cd build
          make
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: chekout
        uses: actions/checkout@v2

      - name: tests
        shell: bash
        run: |
          git submodule update --init --recursive
          cmake -B build
          cd build
          make

