name: building_tests
on: [ push ]
jobs:
  building_gtests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: build
        shell: bash
        run: |
          git submodule add https://github.com/google/googletest third-party/gtest
          cmake -B build
          cd build
          make
    testing:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@master

        - name: test
          shell: bash
          run: |
            git submodule add https://github.com/google/googletest third-party/gtest
            cmake -B build
            cd build
            make ./tests
